name: Run Tests

on:
  pull_request:
  push:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'wget https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64'
      - run: 'sudo mv docker-compose-linux-x86_64 /usr/libexec/docker/cli-plugins/docker-compose'
      - run: 'sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose'

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven Test
        run: ./mvnw test
